version: "3.1"

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      TZ: Asia/Seoul
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
  blue:
    image: demo:latest
    restart: always
    command: "--spring.application.name=blue"
    depends_on:
      - postgres
      - redis
  green:
    image: demo:latest
    restart: always
    command: "--spring.application.name=green"
    depends_on:
      - postgres
      - redis
  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./docker/nginx:/etc/nginx/templates
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - blue
      - green

volumes:
  postgres-volume:
